import Footer from "@/components/shared/Footer";
import Header from "@/components/shared/Header";
import { Inter } from "next/font/google";
import "./globals.css";
import Offer from "@/components/shared/offers/Offer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Smart Tools",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="bg-[#e5e6ea] py-8">
          <div className="max-w-7xl mx-auto min-h-[calc(100vh-300px)]">
            {children}
          </div>
        </div>
        <Offer />
        <Footer />
      </body>
    </html>
  );
}
